spring:
  application:
    name: bizup

  datasource:
    url: jdbc:mysql://localhost:3306/bizup
    username: root
    password: 7337
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method

jwt:
  secret: 66EC7337C2E53C4B15F6C9892FC9466EC7337C2E53C4B15F6C9892FC9466EC7337C2E53C4B15F6C9892FC94
  expiration: 1800000           # Access Token 만료 시간 (30분, 밀리초 단위)
  refreshExpiration: 86400000  # Refresh Token 만료 시간 (24시간, 밀리초 단위)
